Feature/meta tags in on tip pages
Sybit-Education/Coding-Camp-2021 pull request #51
Opened 2021-11-11 11:59 UTC by cedi315

2021-11-11 12:14 UTC, mirko-pleli requested changes
Nur ein paar Kleinigkeiten.

2021-11-11 12:14 UTC, mirko-pleli commented on src/views/Ueber-uns.vue
> +      Während des Coding-Camps haben die die App Mülli gecodet.
**haben die die**

2021-11-11 12:14 UTC, mirko-pleli commented on src/views/Ueber-uns.vue
> +    <small class="grey--text text--lighten-1">Brandon Serra (fehlt auf dem Bild)</small>
Füge bitte noch **Cedric Lange** hinzu, ohne dessen Hilfe dieses Projekt auch nicht diesen Status hätte. :)

2021-11-11 12:14 UTC, mirko-pleli commented on src/views/Ueber-uns.vue
> +    <small class="grey--text text--lighten-1">Brandon Serra (fehlt auf dem Bild)</small>
Ach und Henrik Schmid kannst du ja eigentlich auch hinzufügen.

2021-11-11 14:13 UTC, raphaelschnick approved these changes

2021-11-11 14:20 UTC, stritti commented
Warum hast du die Komponente `TipDetail.vue` raus genommen? Jetzt haben wir da Konflikte mit `develop` ...

2021-11-11 17:17 UTC, stritti commented
Meta-Tags bei allen Views wären  gut. Nicht nur bei den Tipps.
Und die Meta-Tags für die Preview-Bilder

2021-11-11 17:27 UTC, stritti commented
> Meta-Tags bei allen Views wären gut. Nicht nur bei den Tipps. Und die Meta-Tags für die Preview-Bilder

Das metaTemplate habe ich mal hinzugefügt.

2021-11-12 10:45 UTC, stritti commented
![image](https://user-images.githubusercontent.com/184547/141454510-c1eeaaee-e7ee-4ee7-9fc8-9e41f59e05d1.png)

2021-11-12 15:15 UTC, mirko-pleli commented on src/views/Ueber-uns.vue
> +    <small class="grey--text text--lighten-1">Brandon Serra (fehlt auf dem Bild), Henrik Schmid (als Schülerpraktikum)</small>
Cedric Lange fehlt noch :)

2021-11-12 15:15 UTC, mirko-pleli approved these changes

2021-11-12 15:33 UTC, merged