Feature/problemstoffmobil-calendar
Sybit-Education/Coding-Camp-2021 pull request #78
Opened 2022-01-12 10:50 UTC by stritti

* add new view with pickup events of "Problemstoff-Mobil"
* Filter for municipalities

2022-01-12 13:07 UTC, stritti commented
![image](https://user-images.githubusercontent.com/184547/149146047-e0cd87df-b359-43fe-b030-629ecb601a82.png)

2022-01-19 10:16 UTC, raphaelschnick requested changes

2022-01-19 10:16 UTC, raphaelschnick commented on src/components/problemstoffmobil/EventCard.vue
> +  <v-card :id="event.id" class="event-card rounded-xl my-3">
Für was wird die id hier benötigt?

2022-01-19 10:16 UTC, raphaelschnick commented on src/views/ProblemstoffmobilView.vue
> +  <v-container id="problemstoffmobil">
Braucht man die id hier?

2022-01-19 10:16 UTC, raphaelschnick commented on src/views/MapView.vue
> +/* eslint-disable */
Für was wird eslint hier disabled?

2022-01-19 10:20 UTC, raphaelschnick requested changes

2022-01-19 10:20 UTC, raphaelschnick commented on src/views/HomeView.vue
> +  name: 'HomeView',
Ich glaube den `name` in Views kann man hier weglassen, da der sich ja glaub den Namen aus dem `router` nimmt

2022-01-19 16:31 UTC, stritti commented on src/components/problemstoffmobil/EventCard.vue
> +  <v-card :id="event.id" class="event-card rounded-xl my-3">
ja als Sprungmarke, wenn man deep-Links hat.

2022-01-19 16:32 UTC, stritti commented on src/views/ProblemstoffmobilView.vue
> +  <v-container id="problemstoffmobil">
nicht wirklich. habs sie raus genommen.

2022-01-19 16:33 UTC, stritti commented on src/views/MapView.vue
> +/* eslint-disable */
gute Frage ...

2022-01-19 16:34 UTC, stritti commented on src/views/HomeView.vue
> +  name: 'HomeView',
schadet aber auch nicht :)

2022-01-21 15:19 UTC, raphaelschnick approved these changes

2022-01-21 15:36 UTC, merged